version: '3.7'
services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    volumes: 
      - type: volume
        source: timescale-volume
        target: /var/lib/postgresql/data
        read_only: false
    environment:
      POSTGRES_PASSWORD: "password"
    ports: 
      - 0.0.0.0:5432:5432

volumes:
    timescale-volume:
        driver: local